carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

sport247/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('carts/', include('carts.urls')),
    path('store/', include('store.urls')),
    path('orders/', include('orders.urls')),
    # path('categories/', include('categories.urls')),
    path('accounts/', include('accounts.urls')),

    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

carts/models.py
from accounts.models import Account
from django.db import models

from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.quantity * self.product.price

    def __unicode__(self):
        return self.product

store/models.py
from django.urls import reverse
from category.models import Category
from accounts.models import Account
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)    # Khi xóa category thì Product bị xóa
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from store.models import Product, Variation
from carts.models import Cart, CartItem


def _cart_id(request):
    cart_id = request.session.session_key
    if not cart_id:
        cart_id = request.session.create()
    return cart_id

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)    # Get object product
    if current_user.is_authenticated:
        product_variations = list()
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST.get(key)
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variations.append(variation)
                except ObjectDoesNotExist:
                    pass

        is_exists_cart_item = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_exists_cart_item:
            cart_items = CartItem.objects.filter(
                product=product,
                user=current_user
            )
            existing_variation_list = [list(item.variations.all()) for item in cart_items]
            id = [item.id for item in cart_items]
            if product_variations in existing_variation_list:
                idex = existing_variation_list.index(product_variations)
                cart_item = CartItem.objects.get(id=id[idex])
                cart_item.quantity += 1
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    user=current_user,
                    quantity=1
                )
        else:
            cart_item = CartItem.objects.create(
                product=product,
                user=current_user,
                quantity=1
            )
        if len(product_variations) > 0:
            cart_item.variations.clear()
            for item in product_variations:
                cart_item.variations.add(item)
        cart_item.save()
        return redirect('cart')
    else:
        product_variations = list()
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST.get(key)
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variations.append(variation)
                except ObjectDoesNotExist:
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request=request))  # Get cart using the _cart_id
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_exists_cart_item = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_exists_cart_item:
            cart_items = CartItem.objects.filter(
                product=product,
                cart=cart
            )
            existing_variation_list = [list(item.variations.all()) for item in cart_items]
            id = [item.id for item in cart_items]
            if product_variations in existing_variation_list:
                idex = existing_variation_list.index(product_variations)
                cart_item = CartItem.objects.get(id=id[idex])
                cart_item.quantity += 1
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    cart=cart,
                    quantity=1
                )
        else:
            cart_item = CartItem.objects.create(
                product=product,
                cart=cart,
                quantity=1
            )
        if len(product_variations) > 0:
            cart_item.variations.clear()
            for item in product_variations:
                cart_item.variations.add(item)
        cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                id=cart_item_id,
                product=product,
                user=request.user
            )
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
                id=cart_item_id,
                product=product,
                cart=cart
            )
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except Exception:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                id=cart_item_id,
                product=product,
                user=request.user
            )
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request=request))
            cart_item = CartItem.objects.get(
                id=cart_item_id,
                product=product,
                cart=cart
            )
        cart_item.delete()
    except Exception:
        pass
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request=request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = total * 2 / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass    # Chỉ bỏ qua
    print(request.user)
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax if "tax" in locals() else "",
        'grand_total': grand_total if "tax" in locals() else 0,
    }
    return render(request, 'store/cart.html', context=context)

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        # cart = Cart.objects.get(cart_id=_cart_id(request=request))
        cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = total * 2 / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass    # Chỉ bỏ qua
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax if "tax" in locals() else "",
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context=context)

store/views.py
from orders.models import OrderProduct
from django.contrib import messages
from store.forms import ReviewForm
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.db.models import Q

from store.models import Product, ReviewRating
from carts.models import Cart, CartItem
from category.models import Category
from carts.views import _cart_id


def store(request, category_slug=None):
    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.all().filter(category=categories, is_available=True)
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')

    page = request.GET.get('page')
    page = page or 1
    paginator = Paginator(products, 3)
    paged_products = paginator.get_page(page)
    product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context=context)


def product_detail(request, category_slug, product_slug=None):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        cart = Cart.objects.get(cart_id=_cart_id(request=request))
        in_cart = CartItem.objects.filter(
            cart=cart,
            product=single_product
        ).exists()
    except Exception as e:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )

    try:
        orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
    except Exception:
        orderproduct = None

    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    context = {
        'single_product': single_product,
        'in_cart': in_cart if 'in_cart' in locals() else False,
        'orderproduct': orderproduct,
        'reviews': reviews,
    }
    return render(request, 'store/product_detail.html', context=context)


def search(request):
    if 'q' in request.GET:
        q = request.GET.get('q')
        products = Product.objects.order_by('-created_date').filter(Q(product_name__icontains=q) | Q(description__icontains=q))
        product_count = products.count()
    context = {
        'products': products,
        'q': q,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context=context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        try:
            review = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=review)
            form.save()
            messages.success(request, "Thank you! Your review has been updated.")
            return redirect(url)
        except Exception:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, "Thank you! Your review has been submitted.")
                return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
	<div class="container">
		<!-- ============================ COMPONENT 1 ================================= -->
		{% if not cart_items %}
		<h2 class="text-center">Your shopping cart is empty</h2>
		<br />
		<div class="text-center">
			<a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
		</div>
		{% else %}
		<div class="row">
			<aside class="col-lg-9">
				<div class="card">
					<table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
							<tr class="small text-uppercase">
								<th scope="col">Product</th>
								<th scope="col" width="120">Quantity</th>
								<th scope="col" width="120">Price</th>
								<th scope="col" class="text-right" width="200"></th>
							</tr>
						</thead>
						<tbody>
							{% for cart_item in cart_items %}
							<tr>
								<td>
									<figure class="itemside align-items-center">
										<div class="aside">
											<img src="{{ cart_item.product.images.url }}" class="img-sm" />
										</div>
										<figcaption class="info">
											<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
											<p class="text-muted small">
												{% if cart_item.variations.all %}
												{% for variation in cart_item.variations.all %}
												{{ variation.variation_category | capfirst }}: {{ variation.variation_value }}
												<br />
												{% endfor %}
												{% endif %}
											</p>
										</figcaption>
									</figure>
								</td>
								<td>
									<!-- col.// -->
									<div class="col">
										<div class="input-group input-spinner">
											<div class="input-group-prepend">
												<a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}"
													class="btn btn-light" type="button">
													<i class="fa fa-minus"></i>
												</a>
											</div>
											<input type="text" class="form-control" value="{{ cart_item.quantity }}" />
											<div class="input-group-append">
												<form action="{% url 'add_cart' cart_item.product.id %}" method="post">
													{% csrf_token %}
													{% for variation in cart_item.variations.all %}
													<input type="hidden" name="{{ variation.variation_category | lower }}"
														value="{{ variation.variation_value | capfirst }}">
													{% endfor %}
													<button class="btn btn-light" type="submit" id="button-plus">
														<i class="fa fa-plus"></i>
													</button>
												</form>
											</div>
										</div>
										<!-- input-group.// -->
									</div>
									<!-- col.// -->
								</td>
								<td>
									<div class="price-wrap">
										<var class="price">${{ cart_item.sub_total }}</var>
										<small class="text-muted">
											${{ cart_item.product.price }} each
										</small>
									</div>
									<!-- price-wrap .// -->
								</td>
								<td class="text-right">
									<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}"
										class="btn btn-danger" onclick="return confirm('Are you sure?')">
										Remove</a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
			<aside class="col-lg-3">
				<div class="card">
					<div class="card-body">
						<dl class="dlist-align">
							<dt>Total price:</dt>
							<dd class="text-right">${{ total }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Tax:</dt>
							<dd class="text-right">${{ tax }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Total:</dt>
							<dd class="text-right text-dark b">
								<strong>${{ grand_total }}</strong>
							</dd>
						</dl>
						<hr />
						<p class="text-center mb-3">
							<img src="{% static 'images/misc/payments.png' %}" height="26" />
						</p>
						<a href="{% url 'checkout' %}" class="btn btn-primary btn-block">
							Checkout
						</a>
						<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
					</div>
					<!-- card-body.// -->
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
		</div>
		<!-- row.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->
		{% endif %}
	</div>
	<!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <a href="#"><img src="{{ single_product.images.url }}" /></a>
                        </div>
                        <!-- img-big-wrap.// -->
                    </article>
                    <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                            <h2 class="title">{{ single_product.product_name }}</h2>
                            <div class="mb-3">
                                <var class="price h4">${{ single_product.price }}</var>
                            </div>
                            <p>{{ single_product.description }}</p>
                            <hr />
                            <!--<div class="row">-->
                            <!--    <div class="item-option-select">-->
                            <!--        <h6>Choose Color</h6>-->
                            <!--        <select name="color" class="form-select" required>-->
                            <!--            <option value="" disabled selected>Choose color</option>-->
                            <!--            <option value="red">Red</option>-->
                            <!--            <option value="blue">Blue</option>-->
                            <!--            <option value="yellow">Yellow</option>-->
                            <!--            <option value="brown">Brown</option>-->
                            <!--            <option value="pink">Pink</option>-->
                            <!--            {% for variation in single_product.variation_set.colors %}-->
                            <!--            <option value="{{ variation.variation_value | lower }}">{{ variation.variation_value | capfirst }}</option>-->
                            <!--            {% endfor %}-->
                            <!--        </select>-->
                            <!--    </div>-->
                            <!--</div>-->
                            <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-select" required>
                                        <option value="" disabled selected>Choose size</option>
                                        <option value="37">37</option>
                                        <option value="38">38</option>
                                        <option value="39">39</option>
                                        <option value="40">40</option>
                                        <option value="41">41</option>
                                        <option value="42">42</option>
                                        <option value="43">43</option>
                                        <option value="44">44</option>
                                        {% for variation in single_product.variation_set.sizes %}
                                        <option value="{{ variation.variation_value | lower }}">{{ variation.variation_value | capfirst }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <!-- row.// -->
                            <hr />
                            {% if single_product.stock > 0 %} {% if in_cart %}
                            <button type="submit" class="btn btn-success">
                                <span class="text">Add to cart</span>
                                <i class="fas fa-check"></i>
                            </button>
                            <a href="{% url 'cart' %}" class="btn btn-outline-primary">
                                <span class="text">Show cart</span>
                                <i class="fas fa-eye"></i>
                            </a>
                            {% else %}
                            <button type="submit" class="btn btn-primary">
                                <span class="text">Add to cart</span>
                                <i class="fas fa-shopping-cart"></i>
                            </button>
                            {% endif %} {% else %}
                            <h5 class="text-danger">Out of Stock</h5>
                            {% endif %}
                        </article>
                        <!-- product-info-aside .// -->
                    </form>
                </main>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->
        <br />
        <div class="row">
            <div class="col-md-9">
                <form action="{% url 'submit_review' single_product.id %}" method="POST">
                    {% csrf_token %}
                    <h5>Write your review</h5>
                    <div>
                        {% include "includes/alerts.html" %}
                        <label>How do you rate this product?</label>
                        <br>
                        <div class="rate">
							<input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
							<input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
							<input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
							<input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
							<input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
							<input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
							<input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
							<input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
							<input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
							<input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
						</div>
                        <br>
                        Review title:
                        <input type="text" class="form-control" name="subject">
                        <br>
                        Review
                        <textarea name="review" rows="4" class="form-control"></textarea>
                        <br>
                        {% if user.is_authenticated %}
                            {% if orderproduct %}
                            <input type="submit" value="Submit Review" class="btn btn-primary">
                            {% else %}
                            <p>You must purchase this product to post a review.</p>
                            {% endif %}
                        {% else %}
                        <p>You must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
                        {% endif %}
                    </div>
                </form>
                <br>
                <header class="section-heading">
                    <h3>Customer Reviews</h3>
                </header>
                {% for review in reviews %}
                <article class="box mb-3">
                    <div class="icontext w-100">
                        <div class="text">
                            <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
                            <h6 class="mb-1">{{ review.user.full_name }}</h6>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- icontext.// -->
                    <div class="mt-3">
                        <h6>{{ review.subject }}</h6>
                        <p>{{ review.review }}</p>
                    </div>
                </article>
                {% endfor %}
            </div>
            <!-- col.// -->
        </div>
        <!-- row.// -->
    </div>
    <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}